version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  rabbitmq_messaging_console_app:
    build:
      context: .
      dockerfile: RabbitMQMessagingConsoleApp/Dockerfile
    depends_on:
      - rabbitmq

  rabbit_consumer_worker:
    build:
      context: .
      dockerfile: RabbitConsumerWorker/Dockerfile
    depends_on:
      - rabbitmq
